#!/usr/bin/env ruby

require 'rubygems'
require 'git'

g = Git.open('.')

gerrit = 'ssh -p 29418 gerrit.rfiserve.net gerrit'
project = `git remote -v | grep origin | head -1 | cut -d : -f 3 | cut -d / -f 2- | cut -d ' ' -f 1`.strip
commit = g.object('HEAD').sha
reviewers = ARGV

reviewers.each do |reviewer|
  command = "#{gerrit} set-reviewers --project #{project} --add #{reviewer} -- #{commit}"
  p command
  system command
end