#!/usr/bin/env ruby

require 'rubygems'
require 'git'

g = Git.open('.')

gerrit = "ssh -p #{ENV['SSH_PORT']} #{ENV['GERRIT_HOST']} gerrit"
project = `git remote -v | grep origin | head -1 | cut -d : -f 3 | cut -d / -f 2- | cut -d ' ' -f 1`.strip
commit = g.object('HEAD').sha
reviewers = ARGV

command = "#{gerrit} set-reviewers --project #{project} -a #{reviewers.join(" -a ")} -- #{commit}"
p command
system command
